version: '3.8'

services:
  app:
    build: .
    restart: unless-stopped
    ports:
      - "80:80"
      - "8090:8090"
    volumes:
      - ./backend/pb_data:/pb_data
    environment:
      - NODE_ENV=production
      - VIRTUAL_HOST=skiddytamil.in,content.skiddytamil.in
      - LETSENCRYPT_HOST=skiddytamil.in,content.skiddytamil.in
      - LETSENCRYPT_EMAIL=your-email@example.com
    networks:
      - app_network
      - nginx-proxy

networks:
  app_network:
    driver: bridge
  nginx-proxy:
    external: true
