version: '3'

services:
  frontend:
    build: 
      context: .
      args:
        - VITE_API_URL=${VITE_API_URL:-https://skiddy-pocketbase.9dto0s.easypanel.host/}
    container_name: skiddys-frontend
    restart: unless-stopped
    ports:
      - "${PORT:-80}:80"
    environment:
      - VITE_API_URL=${VITE_API_URL:-https://skiddy-pocketbase.9dto0s.easypanel.host/}
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
    networks:
      - app-network
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:80"]
      interval: 30s
      timeout: 10s
      retries: 3
    mem_limit: 512M
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 512M

  pocketbase:
    image: ghcr.io/muchobien/pocketbase:latest
    container_name: skiddys-pocketbase
    restart: unless-stopped
    ports:
      - "8090:8090"
    environment:
      - SMTP_HOST=${SMTP_HOST:-email-smtp.ap-south-1.amazonaws.com}
      - SMTP_PORT=${SMTP_PORT:-587}
      - SMTP_USERNAME=${SMTP_USERNAME}
      - SMTP_PASSWORD=${SMTP_PASSWORD}
      - SMTP_SECURE=${SMTP_SECURE:-true}
    volumes:
      - pb_data:/pb/pb_data
      - pb_migrations:/pb/pb_migrations
      - pb_hooks:/pb/pb_hooks
    networks:
      - app-network
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:8090/api/health"]
      interval: 30s
      timeout: 10s
      retries: 3
    mem_limit: 512M
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 512M

networks:
  app-network:
    driver: bridge

volumes:
  pb_data:
  pb_migrations:
  pb_hooks:
