version: '3.8'

services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./pb_data:/pb_data
      - ./pb_migrations:/pb_migrations
      - ./pb_hooks:/pb_hooks
      - ./ssl:/etc/nginx/ssl
    environment:
      - VITE_API_URL=https://skiddytamil.in
    depends_on:
      - pocketbase

  pocketbase:
    image: ghcr.io/muchobien/pocketbase:latest
    container_name: pocketbase
    restart: unless-stopped
    ports:
      - "8090:8090"
    volumes:
      - ./pb_data:/pb_data
      - ./pb_migrations:/pb_migrations
      - ./pb_hooks:/pb_hooks
      - ./pb_config.json:/pb/pb_config.json
    environment:
      - SMTP_HOST=email-smtp.ap-south-1.amazonaws.com
      - SMTP_PORT=587
      - SMTP_USERNAME=AKIA46BWJRR3A3ZAIEXZ
      - SMTP_PASSWORD=BP/mgFX44Zq55129YEVCBRLXL9l3IVG9JxFITKfm5EMQ
      - SMTP_SECURE=true
    healthcheck:
      test: wget --no-verbose --tries=1 --spider http://localhost:8090/api/health || exit 1
      interval: 5s
      timeout: 5s
      retries: 5

  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - ./dist:/usr/share/nginx/html
      - ./ssl:/etc/nginx/ssl
    depends_on:
      - frontend
      - pocketbase
