version: '3.8'

services:
  app:
    build: .
    restart: unless-stopped
    ports:
      - "80:80"
      - "8090:8090"
    volumes:
      - ./backend/pb_data:/pb_data
    environment:
      - NODE_ENV=development
    networks:
      - app_network

networks:
  app_network:
    driver: bridge
