version: '3'

services:
  frontend:
    image: ghcr.io/rizo8107/skiddys-learning-platform-frontend:latest
    container_name: skiddys-frontend
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    environment:
      - VITE_API_URL=https://skiddytamil.in/api
    volumes:
      - ./dist:/usr/share/nginx/html
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - ./ssl:/etc/nginx/ssl
    networks:
      - default
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:80"]
      interval: 30s
      timeout: 10s
      retries: 3
    mem_limit: 512M

  pocketbase:
    image: ghcr.io/muchobien/pocketbase:latest
    container_name: skiddys-pocketbase
    restart: unless-stopped
    ports:
      - "8090:8090"
    environment:
      - SMTP_HOST=email-smtp.ap-south-1.amazonaws.com
      - SMTP_PORT=587
      - SMTP_USERNAME=AKIA46BWJRR3A3ZAIEXZ
      - SMTP_PASSWORD=BP/mgFX44Zq55129YEVCBRLXL9l3IVG9JxFITKfm5EMQ
      - SMTP_SECURE=true
    volumes:
      - ./pb_data:/pb/pb_data
      - ./pb_migrations:/pb/pb_migrations
      - ./pb_hooks:/pb/pb_hooks
      - ./pb_config.json:/pb/pb_config.json
    networks:
      - default
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:8090/api/health"]
      interval: 30s
      timeout: 10s
      retries: 3
    mem_limit: 512M

networks:
  default:
    driver: bridge

volumes:
  pb_data:
  pb_migrations:
  pb_hooks:
  ssl:
