[build]
  base = "/"
  command = "npm run build"
  publish = "dist"
  functions = "netlify/functions"

[build.environment]
  NODE_VERSION = "18"
  VITE_POCKETBASE_URL = "http://127.0.0.1:8090"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
